#!/usr/bin/env node
const { exec } = require('child_process')

const gitDiff = exec("git diff --cached --name-only --diff-filter=ACM | cat")

gitDiff.stdout.on("data", (data) => {
  const files = data.trim().split("\n")

  const areChangesInFunctionFiles = files.map((file) => {
    const isChangeInFunctionsDir = /...\/functions\//.test(file)
    const isIndexFile = /...\/functions\/index/.test(file)
    const isTestFile = /...\/functions\/__tests__/.test(file)
    return isChangeInFunctionsDir && !(isIndexFile || isTestFile)
  })

  if (areChangesInFunctionFiles.includes(true)) {
    console.log("Change detected in function file. Compiling...\n")
    exec("make types && git add editor/functions.d.ts", (error, stdout, stderr) => {
      if (error) {
        console.log("There was an error compiling functions.d.ts:\n", stderr)
      } else {
        console.log("functions.d.ts successfully compiled, added to commit.\n")
      }
    })
  } else {
      console.log("No changes detected in functions files\n")
  }
})
