#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
root_dir=${script_dir}/..

ENVIRONMENT="${USER}"

if [[ -n "${1:-}" ]]
then
  ENVIRONMENT="${1}"
fi

if [[ "${ENVIRONMENT}" == "production" ]]
then
  printf "\nYOU ARE DEPLOYING TO PRODUCTION!!\n\n"
  read -p "Are you sure you want to continue? (N/y): " confirmation
  if [[ "${confirmation}" != "y" && "${confirmation}" != "Y" ]]
  then
    printf "Deployment cancelled\n"
    exit 1
  fi
  bucket=fulcrum-assets
else
  bucket=fulcrumapp-world-${ENVIRONMENT}
fi

aws s3 cp \
  --cache-control "no-cache, no-store, max-age=0, must-revalidate" \
  --expires "Mon, 01 Jan 1990 00:00:00 GMT" \
  --content-type "application/javascript" \
  --acl "public-read" \
  ${root_dir}/dist/expressions.js s3://${bucket}/expv1/expressions.js

printf "Deployed https://${bucket}.s3.amazonaws.com/expv1/expressions.js\n"

aws s3 cp \
  --cache-control "no-cache, no-store, max-age=0, must-revalidate" \
  --expires "Mon, 01 Jan 1990 00:00:00 GMT" \
  --content-type "application/javascript" \
  --acl "public-read" \
  ${root_dir}/dist/expressions-proxy.js s3://${bucket}/expv1/expressions-proxy.js

printf "Deployed https://${bucket}.s3.amazonaws.com/expv1/expressions-proxy.js\n"

aws s3 cp \
  --cache-control "no-cache, no-store, max-age=0, must-revalidate" \
  --expires "Mon, 01 Jan 1990 00:00:00 GMT" \
  --content-type "text/html" \
  --acl "public-read" \
  ${root_dir}/dist/expressions.html s3://${bucket}/expv1/expressions.html

printf "Deployed https://${bucket}.s3.amazonaws.com/expv1/expressions.html\n"
